### ISSUE TITLE
Can you upload the script/code to convert the dataset to LevelDB

### ISSUE THREAD

**Issue by huangjq0617** [YerevaNN/Spoken-language-identification#1]
Your blog and code help me a lot! Thank you very much.
But I'm new to caffee, and don't how to convert the dataset to LevelDB.
Can you please upload the script or code to do it ? Thank you again!

**Comment by hrayrhar** [comment]
You can use `convert_imageset` in `$CAFFE_ROOT/build/tools` to crate a lmdb/leveldb. [Here ](http://stackoverflow.com/questions/31427094/guide-to-use-convert-imageset-cpp) is described how to use it.
