### ISSUE TITLE
Can you explain how to run properly with Theano build?

### ISSUE THREAD

**Issue by areibman** [YerevaNN/Spoken-language-identification#2]
Hi! I love your blog! I'm trying to try this on my own machine for a class project, but I'm running into some problems running the program correctly. I'm new to python so I don't know exactly how to run it, but after configuring the correct dependencies, I still ran into some issues trying it for myself. Here are the parameters I used for the Theano [combined CNN RNN project](http://yerevann.github.io/2016/06/26/combining-cnn-and-rnn-for-spoken-language-identification/):

`# TODO: add argument to choose training set
parser.add_argument('--network', type=str, default="tc_net_mod", help='embeding size (50, 100, 200, 300 only)')
parser.add_argument('--epochs', type=int, default=500, help='number of epochs to train')

parser.add_argument('--load_state', type=str, default="", help='state file path')

parser.add_argument('--mode', type=str, default="train", help='mode: train/test/test_on_train')

parser.add_argument('--batch_size', type=int, default=32, help='no commment')

parser.add_argument('--l2', type=float, default=0, help='L2 regularization')

parser.add_argument('--log_every', type=int, default=100, help='print information every x iteration')

parser.add_argument('--save_every', type=int, default=50000, help='save state every x iteration')

parser.add_argument('--prefix', type=str, default="", help='optional prefix of network name')

parser.add_argument('--dropout', type=float, default=0.0, help='dropout rate (between 0 and 1)')

parser.add_argument('--no-batch_norm', dest="batch_norm", action='store_false', help='batch normalization')

parser.add_argument('--rnn_num_units', type=int, default=500, help='number of hidden units if the network is RNN')

parser.add_argument('--equal_split', type=bool, default=False, help='use trainEqual.csv and valEqual.csv')

parser.add_argument('--forward_cnt', type=int, default=1,
                    help='if forward pass is nondeterministic, then how many forward passes are averaged')`

I chose to keep everything mostly default except the first argument where I replace "network_batch" with "tc_net_mod" because I get an error otherwise.

Specifically, I don't know what the file path should be for this argument:
`parser.add_argument('--load_state', type=str, default="", help='state file path')
`
When I try the .Zip folder with the training data from the Topcoder competition, I get this error:

> `Traceback (most recent call last):
>   File "C:/Users/Alex/PycharmProjects/Spoken-language-identification/theano/main.py", line 76, in <module>
>     start_epoch = network.load_state(args.load_state) + 1
>   File "C:\Users\Alex\PycharmProjects\Spoken-language-identification\theano\networks\base_network.py", line 23, in load_state
>     dict = pickle.load(load_file)
> cPickle.UnpicklingError: A load persistent id instruction was encountered,
> but no persistent_load function was specified.`

I really want to see if I can get this working, It would be great if you could show a how-to guide :)

**Comment by hrayrhar** [comment]
Hi, sorry for late response,
`load_state` argument is designed for loading a state file of some network (not for data). If you want to run the code, you should download dataset from TopCoder, create  the spectrograms of recordings, split them into train and validation sets and then change the paths which are used for loading data in `main.py` file.

**Comment by areibman** [comment]
Hey thanks for the response! 

Just a few notes, some of the files need to be modified to get the program to work properly. I'm probably just doing something really stupid, but I still haven't been able to get the program to work properly. Here are the steps I took (wall of text incoming!):

If the trainingData.csv from the top coder website isn't modified, you get a string to int error. To solve this, you need to replace the 2nd column that of the testing data that contains names with numbers. I did this by creating a simple string to int hashing function in Microsoft Excel.

This also isn't enough for the program to function. You need to further modify the .csv to reflect the the png image files made by augment_data.py Augment_data.py creates 20 slightly random variations of the spectrogram for each image. However, by using trainingData.csv, the networks assume that there is only a single image. 

To get around this, again, the trainingDava.csv needs to be modified. I did this by removing the .mp3 from each string, and adding ".n" for each specific file, and making n copies of each file. So for example, if trainingData.csv has the entry 3jskfd1.mp3, I will modify trainingData.csv it so that it now has 20 entries instead of 1. These would be: 3jskfd1.0. ; 3jskfd1.1 ; 3jskfd1.2 ; .... 3jskfd1.19 . This way, when the following code executes, the proper files in the /png/ directory are located

I made a short Java program that changes the .csv to correspond with all of the .png files here: https://github.com/areibman/FixCSV

However, the modified csv also leads to some problems. 
In this portion of tc_net_rnn_shared_pad_augm.py, the following error occurs:

> /theano\networks\tc_net_rnn_shared_pad_augm.py", line 201, in read_batch
>     data[i - start_index, 0, :, :] = np.array(im).astype(np.float32)[:128, offset:offset+768] / 256.0
> ValueError: could not broadcast input array from shape (128,733) into shape (128,768)

I suspected that the random offset implemented might have been interfering, so I tried setting it to 0. However, it throws yet another error:

> ValueError: y_i value out of bounds
> Apply node that caused the error: CrossentropySoftmaxArgMax1HotWithBias(Dot22.0, b, answer_var)
> Toposort index: 1008
> Inputs types: [TensorType(float64, matrix). TensorType(float64, vector), TensorType(int32, vector)]
> Inputs shapes: [(32, 176), (176,), (32,)]
> Inputs strides: [(1408,8), (8,), (4,)]
> Inputs values: ['not shown', 'not shown', 'not shown']

What would you suggest?

**Comment by hrayrhar** [comment]
Hi !  
Seems you have created the `.csv` file correctly. The problem is that I didn't use data augmentation in theano/lasagne models (the second blogpost), data augmentation was used in earlier caffe models (the first blogpost). So all networks in `theano/networks` folder expect  `256x858` images. Some of these networks will then use only the half of the frequencies (`128x858` image, up to `5khz`). Only one of these networks (`tc_net_rnn_shared_pad_augm.py`) does data augmentation by randomly cropping `128x768` part from `128x858` image. So to run the code you should create spectrograms which have 858px width. To do so you can use `augment_data.py`, but set `alpha=1.0` and don't crop 9s part from the speech. It should look like [this](https://gist.github.com/Harhro94/b4bd3fdda7146b62526dab26b47a03bf) . Also you need to remove `.n` from the `.csv` file and delete copies. The `.csv` file should look like [this](https://gist.github.com/Harhro94/aa11fe6b454c614cdedea882fd00f8d7).

**Comment by areibman** [comment]
Cool,  thanks for the clarification. 

Unfortunately, I'm still getting the same error (see below). It doesn't seem that formatting the data correctly had any effect. I think that this is possibly because I'm using Windows or my environment isn't correctly set up. I attached a zip with about 30 of the spectrograms and the csv I'm using

Sorry to bother you so much! I just think this is an incredibly cool idea, and I was interested in seeing what this is capable of. I was interested in seeing how far this could go in recognizing smaller nuances in language. For example, a lot of systems have difficulty distinguishing between women and children. My professor actually has a sizable database of these files and said I could test it for an end of term project.

[Data.zip](https://github.com/YerevaNN/Spoken-language-identification/files/442007/Data.zip)

`Traceback (most recent call last):
  File "C:/Users/Akrylic/PycharmProjects/Spoken-language-identification/theano/main.py", line 130, in <module>
    do_epoch('train', epoch)
  File "C:/Users/Akrylic/PycharmProjects/Spoken-language-identification/theano/main.py", line 82, in do_epoch
    step_data = network.step(i, mode)
  File "C:\Users\Akrylic\PycharmProjects\Spoken-language-identification\theano\networks\base_network.py", line 57, in step
    ret = theano_fn(data, answers)
  File "C:\Users\Akrylic\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\theano\compile\function_module.py", line 871, in **call**
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\Users\Akrylic\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\theano\gof\link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\Users\Akrylic\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\theano\compile\function_module.py", line 859, in **call**
    outputs = self.fn()

ValueError: y_i value out of bounds
Apply node that caused the error: CrossentropySoftmaxArgmax1HotWithBias(Dot22.0, b, answer_var)
Toposort index: 292
Inputs types: [TensorType(float64, matrix), TensorType(float64, vector), TensorType(int32, vector)]
Inputs shapes: [(32L, 176L), (176L,), (32L,)]
Inputs strides: [(1408L, 8L), (8L,), (4L,)]
Inputs values: ['not shown', 'not shown', 'not shown']
Outputs clients: [[Sum{acc_dtype=float64}(CrossentropySoftmaxArgmax1HotWithBias.0)], [CrossentropySoftmax1HotWithBiasDx(Elemwise{inv,no_inplace}.0, CrossentropySoftmaxArgmax1HotWithBias.1, answer_var), 'output'], []]
`

**Comment by hrayrhar** [comment]
The last softmax layer has 176 neurons. When the cross entropy is calculated, it needs the true labels to be integers from [0, 176). In your mapping from languages to integers you used numbers greater than 175.
[This](https://github.com/YerevaNN/Spoken-language-identification/files/444448/mapping.zip) is the mapping I used (I didn't push these files because, as I remember, the training data was not open). 
I'n not sure the code will work on Windows, I haven't tested on Windows. On the other hand, as it fails to calculate the cross entropy (which means it has already forwarded an example successfully) probably it will work.
