### ISSUE TITLE
question_of_augment_data.py

### ISSUE THREAD

**Issue by xuzero** [YerevaNN/Spoken-language-identification#4]
Thanks for your sharing!
Could you please explain why is the offset:offset+768,which is in the line 77 of augment_data.py .   
768 is only  for your data or every audio is 768 for 9 seconds?What can influence the number to represent
 9 seconds?sample rate?

**Comment by hrayrhar** [comment]
In augment.py we not only create spectrograms, but also augment the data by randomly croping 9s parts and randomly warping the recording. This augmentation is done to reduce overfitting, but you can skip the augmenation (the results will be almost the same) by creating the spectrograms using create_spectrograms.py.

Hrayr

**Comment by xuzero** [comment]
Thanks for your answer!
But i still don not know why is 768 for the 9 seconds in your code?How can get my number for my own data? Is it related to sample rate?

**Comment by hrayrhar** [comment]
I had 10s recordings, which result spectrograms of size 128x858 (or
256x858), so for ~9s parts it is convenient take parts with 768 pixels (3 *
256).

Hrayr

**Comment by xuzero** [comment]
Thanks for your reply!
 If the size  of spectrogram is 256x858, 256 respresent the 11khz frequencies，858 respresent the 10s, 9s should be 858*0.9=772.2 ,but why 768?
I also have another question ,your cnn model is finetuned from AlexNet which is trained ImageNet or you train the cnn model from scratch on your data? Have you tried both methods?Thank you very much!

**Comment by hrayrhar** [comment]
There is no constraint to have exactly 9s. I think 768 is a nice number :) 
I have trained all models from scratch and haven't tried to use pretrained networks.
