### ISSUE TITLE
How to use GPU

### ISSUE THREAD

**Issue by xuzero** [YerevaNN/Spoken-language-identification#5]
Thanks for your sharing !
I run your great code successfully, but i have a question,my dataset have 0.6 million images and 20 classes,which is so slow if i only use the cpu, Could you please tell me how to use GPU with your code?
I have 8 nvidia k80 GPUs on my server.And how to use the multiple gpu to  accelerate?
BTW,I have install cuda and cudnn successfully.

**Comment by hrayrhar** [comment]
To use a GPU, run the code this way `THEANO_FLAGS='device=gpu' python file [arguments]`.
I don't know how to use multiple GPUs, seems [this](http://deeplearning.net/software/theano/tutorial/using_multi_gpu.html) is the right place to look.
