### ISSUE TITLE
Can we apply this combination of CNN_RNN for all types of images ?

### ISSUE THREAD

**Issue by dolphina** [YerevaNN/Spoken-language-identification#8]
Hello,

Please, I want to know if we can apply this idea for all kind of images. Here, you used spectrograms where the axis are about the time, this is why you applied RNN to the CNN? RNN can not be applied to static features.

**Comment by Hrant-Khachatrian** [comment]
You can apply it to everything. But I think end-to-end CNNs are better for images

**Comment by dolphina** [comment]
Thanks for your prompt reply. Actually, I am working on medical images classification. I have already used CNN and now I want to test CNN combined with RNN. So I thought to use your idea here. I searched on the Internet and I found that I can make the convolution and pooling layers distributed across time using Keras. And then give the last pooling layer as input to RNN. Can you please give me your opinion about this idea. And which one is better yours or the one I told. Thanks

**Comment by Hrant-Khachatrian** [comment]
I don't think that RNNs will increase accuracy over pure CNNs for such tasks. But, as you know, there is no theory on that, so you can test all versions

**Comment by dolphina** [comment]
Thanks.
